name: auto-format
on: pull_request
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Format with spotless
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessApply

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Wynntils'
          git config --global user.email 'admin@wynntils.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "chore: spotless formatting"
          git push
