name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x spotlessCheck --no-daemon
