on:
  workflow_call:
    inputs:
      file_path:
        required: true
        type: string
      release_name:
        required: true
        type: string
      tag:
        required: true
        type: string
      changelog:
        required: true
        type: string
      cf_mc_version:
        required: true
        type: string
      mr_mc_version:
        required: true
        type: string
      mr_loader:
        required: true
        type: string
    secrets: inherit

  release-to-cf:
    name: Release to CurseForge
    runs-on: ubuntu-latest
    needs: [changelog, artifact]
    steps:
      - uses: actions/download-artifact@v3

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: "${{ inputs.file_path }}"
          game_endpoint: minecraft
          game_versions: "${{ inputs.cf_mc_version }}"
          project_id: 303451
          token: ${{ secrets.CF_API_TOKEN }}
          release_type: beta
          display_name: "${{ inputs.release_name }}"
          changelog_type: markdown
          changelog: "${{ needs.changelog.outputs.changelog }}"

  release-to-modrinth:
    name: Release to Modrinth
    runs-on: ubuntu-latest
    needs: [changelog, artifact]
    steps:
      - uses: actions/download-artifact@v3

      - name: Upload to Modrinth
        uses: RubixDev/modrinth-upload@v1.0.0
        with:
          token: ${{ secrets.MODRINTH_API_TOKEN }}
          file_path: "${{ inputs.file_path }}"
          name: "${{ inputs.release_name }}"
          version: "${{ inputs.tag }}"
          changelog: "${{ inputs.changelog }}"
          game_versions: "${{ inputs.mr_mc_version }}"
          release_type: beta
          loaders: "${{ inputs.mr_loader }}"
          featured: false
          project_id: dU5Gb9Ab
